import { useNavigate } from 'react-router-dom';
import { useAuthStore } from '@/store';
import styles from './LandingPage.module.css';

const DOMAINS = [
  { icon: '💻', label: 'Software Engineer' },
  { icon: '📊', label: 'Data Scientist' },
  { icon: '🗂️', label: 'Product Manager' },
  { icon: '🎨', label: 'UI/UX Designer' },
  { icon: '⚙️', label: 'DevOps Engineer' },
];

const FEATURES = [
  {
    icon: '🧠',
    title: 'AI Interviewer',
    desc: 'Dynamic domain-specific questions generated by Google Gemini 2.5 Flash — no two interviews are the same.',
  },
  {
    icon: '👁️',
    title: 'On-Device Vision AI',
    desc: 'MediaPipe Face Mesh runs directly in your browser GPU. Real-time confidence tracking at 30 FPS — zero data sent to servers.',
  },
  {
    icon: '🎙️',
    title: 'Voice Recognition',
    desc: 'Groq Whisper transcribes your answers in under a second — the fastest speech-to-text available today.',
  },
  {
    icon: '📈',
    title: 'Instant Feedback',
    desc: 'Every answer is scored and detailed feedback is shown immediately. Strengths and improvements at a glance.',
  },
  {
    icon: '📋',
    title: 'Report & History',
    desc: 'Full interview report saved to your account. Track score trends across sessions to measure real progress.',
  },
  {
    icon: '📱',
    title: 'Installable PWA',
    desc: 'Install on any device — works offline, launches instantly, feels like a native app.',
  },
];

export default function LandingPage() {
  const navigate = useNavigate();
  const { user } = useAuthStore();

  const handleStart = () => {
    navigate(user ? '/interview' : '/auth');
  };

  return (
    <div className={styles.page}>
      {/* Ambient background orbs */}
      <div className={styles.orb1} />
      <div className={styles.orb2} />
      <div className={styles.orb3} />

      {/* ── Navbar ── */}
      <nav className="navbar">
        <div className="container" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div className={styles.logo}>
            <span className="gradient-text">AIVOX</span>
          </div>
          <div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}>
            {user ? (
              <>
                <button className="btn btn-ghost btn-sm" onClick={() => navigate('/dashboard')}>Dashboard</button>
                <button className="btn btn-primary btn-sm" onClick={() => navigate('/interview')}>Start Interview</button>
              </>
            ) : (
              <button className="btn btn-primary btn-sm" onClick={() => navigate('/auth')}>Sign In</button>
            )}
          </div>
        </div>
      </nav>

      {/* ── Hero ── */}
      <section className={`section ${styles.hero}`}>
        <div className="container" style={{ textAlign: 'center' }}>
          <div className={`badge badge-accent ${styles.heroBadge} animate-fade-in`}>
            ✨ AI-Powered Mock Interviews
          </div>
          <h1 className={`animate-fade-in-up ${styles.heroTitle}`}>
            Ace Every Interview<br />
            with <span className="gradient-text">AI Coaching</span>
          </h1>
          <p className={`${styles.heroSubtitle} animate-fade-in-up`}>
            Real-time facial confidence tracking, instant voice transcription,<br className={styles.desktopBr} />
            and detailed AI feedback — all running in your browser.
          </p>
          <div className={styles.heroCta}>
            <button className="btn btn-primary btn-lg" onClick={handleStart} id="hero-cta-btn">
              🚀 Start Free Interview
            </button>
            <a className="btn btn-ghost btn-lg" href="#features">See How It Works</a>
          </div>

          {/* Domain pills */}
          <div className={styles.domainPills}>
            {DOMAINS.map(d => (
              <span key={d.label} className={`glass-card ${styles.domainPill}`}>
                {d.icon} {d.label}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ── Stats ── */}
      <section className={styles.statsBar}>
        <div className="container">
          <div className={styles.statsGrid}>
            {[
              { val: '19×', label: 'Faster than CNN' },
              { val: '30 FPS', label: 'Confidence Tracking' },
              { val: '<1s', label: 'Transcription Speed' },
              { val: '$0', label: 'Cost to You' },
            ].map(s => (
              <div key={s.label} className={styles.statItem}>
                <div className={styles.statVal}>{s.val}</div>
                <div className={styles.statLabel}>{s.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features ── */}
      <section className="section" id="features">
        <div className="container">
          <div style={{ textAlign: 'center', marginBottom: '56px' }}>
            <h2>Everything You Need to <span className="gradient-text">Prepare</span></h2>
            <p style={{ marginTop: '16px', maxWidth: '520px', margin: '16px auto 0' }}>
              Professional-grade interview coaching technology, packaged in a free, installable web app.
            </p>
          </div>
          <div className={styles.featuresGrid}>
            {FEATURES.map(f => (
              <div key={f.title} className={`glass-card ${styles.featureCard}`}>
                <div className={styles.featureIcon}>{f.icon}</div>
                <h3 style={{ fontSize: '1.1rem', marginBottom: '8px' }}>{f.title}</h3>
                <p style={{ fontSize: '0.9rem', lineHeight: '1.6' }}>{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA Banner ── */}
      <section className={`section ${styles.ctaBanner}`}>
        <div className="container" style={{ textAlign: 'center' }}>
          <h2>Ready to Practice?</h2>
          <p style={{ margin: '16px 0 32px' }}>No credit card. No setup. Just sign in and start.</p>
          <button className="btn btn-primary btn-lg" onClick={handleStart}>
            Get Started Free →
          </button>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer className={styles.footer}>
        <div className="container" style={{ textAlign: 'center' }}>
          <div className={styles.logo} style={{ justifyContent: 'center', marginBottom: '8px' }}>
            <span className="gradient-text">AIVOX</span>
          </div>
          <p style={{ fontSize: '0.85rem' }}>AI Interview Coach · Built with Gemini, Groq, MediaPipe & Firebase</p>
          <p style={{ fontSize: '0.8rem', marginTop: '8px', color: 'var(--text-muted)' }}>
            Educational project · For demonstration purposes
          </p>
        </div>
      </footer>
    </div>
  );
}
